### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by ZanebonoAlter** [WHALEEYE/Palworld-Server-Monitoring#1]
小黑盒看到来的，首先感谢分享的脚本
是否考虑用一个restart脚本使用systemctl restart palw.service 代替service的24h配置（如果是中午12点开服的，明天12点就寄了）
然后cron表达式配置个比如5 2 * * * /home/steam/restart.sh来实现凌晨的重启

**Comment by WHALEEYE** [comment]
对于这点我的想法是，确实需要根据实际情况略微修改最大运行时间，我这里写的24h有些长了。目前我已经将服务器上的最大运行时间改为了12h。

另外，看到了编辑之前关于备份的问题。这点其实确实是一个值得讨论的点，因为我的考量是游戏应该是定期进行序列化的（当右上角出现Saving的时候），因此在备份过程中出现数据变更的概率不大（当然这点我并不确定，因此这个假设可能是有问题的）。同时，由于我备份间隔在2小时，因此每次备份对服务重启的话可能过于频繁了，于是就还是采用了设置服务最大运行时间的方式，将备份和重启操作以异步的方式进行。

不过，经你提醒后，我觉得在游戏运行中进行备份确实存在隐患，因此更新了服务参数和脚本，使其在服务停止（因为任何原因）后进行一次备份，以防万一。

感谢你的建议！
